-- Deepen questionnaire for marriage-oriented matching (same version 1 as initial seed).
-- After applying: existing users should revisit /onboarding/quiz to answer new required items before re-running "finish" if needed.
-- Roadmap: surface overlaps in a future "Things in common" tab from questions + answers.

insert into public.questions (version, sort_order, section, prompt, answer_type, options, weight, required, dealbreaker)
values
  (1, 9, 'Faith & values', 'How important is it that your partner shares your broad worldview (faith, meaning, purpose)?', 'likert',
   '["Not very","Somewhat","Very","Essential"]'::jsonb, 2, true, false),
  (1, 10, 'Faith & values', 'Are you open to interfaith marriage with mutual respect for each other''s practice?', 'single',
   '["Yes, with clear boundaries","Open if children follow one path","Prefer same faith","Not open"]'::jsonb, 2, true, false),
  (1, 11, 'Faith & values', 'How do you want faith reflected in a future household (rituals, holidays, education)?', 'single',
   '["Central in daily life","Weekly or major holidays","Personal, low visibility in home","Still figuring it out"]'::jsonb, 1.5, true, false),
  (1, 12, 'Faith & values', 'Attending communal worship (as a couple) should be:', 'likert',
   '["Rarely","Monthly or so","Most weeks","A non-negotiable rhythm"]'::jsonb, 1.5, true, false),

  (1, 13, 'Children & family', 'Ideal number of children (if any), honest range:', 'single',
   '["0","1","2","3+","Unsure — want to discuss"]'::jsonb, 2.5, true, false),
  (1, 14, 'Children & family', 'If biology is difficult, openness to adoption or foster care:', 'single',
   '["Very open","Open after trying other options","Unlikely","Not open"]'::jsonb, 2, true, false),
  (1, 15, 'Children & family', 'Preferred childcare approach with young children:', 'single',
   '["A parent at home if possible","Daycare / nanny mix","Grandparents or extended family","Highly situational"]'::jsonb, 1.5, true, false),
  (1, 16, 'Children & family', 'Discipline philosophy you lean toward:', 'single',
   '["Firm boundaries + warmth","Natural consequences heavy","Gentle / minimal punishment","Co-parenting books / therapy-guided"]'::jsonb, 1.5, true, false),
  (1, 17, 'Children & family', 'How often do you expect to see extended family after marriage?', 'likert',
   '["Rarely","A few times a year","Monthly or so","Weekly or more"]'::jsonb, 1.5, true, false),
  (1, 18, 'Children & family', 'If parents need care in old age, your default stance:', 'single',
   '["We support in our home if needed","Nearby / shared sibling duty","Paid care first, family supplements","Case-by-case"]'::jsonb, 1.5, true, false),

  (1, 19, 'Money & marriage', 'Transparency about income, debt, and spending before engagement should be:', 'likert',
   '["Gradual","Before serious commitment","Full transparency early","I am already very open"]'::jsonb, 2, true, false),
  (1, 20, 'Money & marriage', 'Who manages day-to-day budgeting in your ideal marriage?', 'single',
   '["Joint decisions + one executor","Fully joint on everything","Separate accounts + shared bills","We will design a hybrid"]'::jsonb, 1.5, true, false),
  (1, 21, 'Money & marriage', 'Comfort with partner earning significantly more than you:', 'likert',
   '["Uncomfortable","Takes adjustment","Comfortable","No issue at all"]'::jsonb, 1.5, true, false),
  (1, 22, 'Money & marriage', 'Saving for emergencies and retirement should start:', 'single',
   '["Immediately when combined finances","After major wedding expenses","Once income stabilizes","I already prioritize this"]'::jsonb, 1.5, true, false),
  (1, 23, 'Money & marriage', 'Attitude toward debt entering marriage (student loans, etc.):', 'single',
   '["Pay down aggressively together","Split responsibility by agreement","Minimal tolerance for new debt","Discuss case by case"]'::jsonb, 2, true, false),
  (1, 24, 'Money & marriage', 'Large purchases (car, trip) over an agreed threshold should be:', 'single',
   '["Discuss always","Notify + trust unless unusual","Either can decide","We will define a number together"]'::jsonb, 1.25, true, false),

  (1, 25, 'Communication & conflict', 'After a fight, you usually need:', 'single',
   '["Immediate repair attempt","Several hours alone","Sleep on it","Written notes then talk"]'::jsonb, 1.75, true, false),
  (1, 26, 'Communication & conflict', 'Comfort bringing up sensitive topics (money, intimacy, in-laws):', 'likert',
   '["Avoid until necessary","Uneasy but willing","Generally direct","Proactive and calm"]'::jsonb, 1.75, true, false),
  (1, 27, 'Communication & conflict', 'Willingness to attend couples counseling preventively (not only in crisis):', 'likert',
   '["Unlikely","If partner asks","Open yearly check-ins","Already a believer in it"]'::jsonb, 1.5, true, false),
  (1, 28, 'Communication & conflict', 'How do you feel about phones at meals and in bedroom?', 'multi',
   '["No phones at shared meals","Phones ok if urgent","Bedroom mostly screen-free","No strong rules"]'::jsonb, 1, true, false),
  (1, 29, 'Communication & conflict', 'Expressing appreciation (words of affirmation) in daily life:', 'likert',
   '["Unnatural for me","Occasional","Regular","Very important"]'::jsonb, 1.25, true, false),

  (1, 30, 'Lifestyle & home', 'Division of household chores in your vision:', 'single',
   '["Strictly equal lists","By skill and preference","Outsource what we can","Traditional split is fine if agreed"]'::jsonb, 1.5, true, false),
  (1, 31, 'Lifestyle & home', 'How tidy should shared spaces be?', 'likert',
   '["Relaxed","Moderate","Quite orderly","Very neat"]'::jsonb, 1.25, true, false),
  (1, 32, 'Lifestyle & home', 'Pets in the home:', 'single',
   '["Must have","Open","Prefer none","Allergies / strong no"]'::jsonb, 1.5, true, false),
  (1, 33, 'Lifestyle & home', 'Ideal weeknight energy after work:', 'single',
   '["Homebodies","Out a few nights","Gym or hobbies solo","Mix — negotiate weekly"]'::jsonb, 1.25, true, false),
  (1, 34, 'Lifestyle & home', 'Dietary pattern that matters for a shared kitchen:', 'multi',
   '["No restrictions","Halal / kosher considerations","Vegetarian or vegan","Allergies are serious"]'::jsonb, 1.25, true, false),
  (1, 35, 'Lifestyle & home', 'How much solo time or friend time do you need weekly?', 'single',
   '["Almost none","A few hours","One full evening","Significant — non-negotiable"]'::jsonb, 1.5, true, false),

  (1, 36, 'Commitment & vision', 'Relocating for a spouse''s career opportunity:', 'single',
   '["Willing if discussed","Once or twice max","Very reluctant","Would not move"]'::jsonb, 2, true, false),
  (1, 37, 'Commitment & vision', 'How do you view emotional intimacy with close friends of the gender you are attracted to?', 'single',
   '["No deep one-on-one friendships","Transparency + boundaries ok","Trust-based, case by case","Not a concern"]'::jsonb, 2, true, false),
  (1, 38, 'Commitment & vision', 'Expectation around sharing phone / social passwords:', 'single',
   '["Never","If crisis only","Some shared access","Full openness"]'::jsonb, 1.5, true, false),
  (1, 39, 'Commitment & vision', 'Working long hours regularly (50+) for career season:', 'likert',
   '["Unacceptable long-term","Short seasons ok","Expected in my field","We will cap it together"]'::jsonb, 1.5, true, false),
  (1, 40, 'Commitment & vision', 'Retirement age or financial independence target mindset:', 'single',
   '["Early if possible","Traditional mid-60s","Work as long as healthy","Not thought through yet"]'::jsonb, 1.25, true, false),

  (1, 41, 'Health & boundaries', 'Physical exercise and health habits — expectation for a partner:', 'single',
   '["No expectation","Some shared activity","Very important we align","I have strict health needs"]'::jsonb, 1.25, true, false),
  (1, 42, 'Health & boundaries', 'Mental health support (therapy, medication) for self or spouse:', 'single',
   '["Fully supportive","Supportive if private","Unsure / stigma","Prefer not to discuss"]'::jsonb, 1.5, true, false),
  (1, 43, 'Intimacy & boundaries', 'Frequency of physical affection you hope for in a stable marriage:', 'likert',
   '["Low need","Moderate","High","Very high"]'::jsonb, 2, true, false),
  (1, 44, 'Intimacy & boundaries', 'Discussing intimacy preferences before marriage:', 'likert',
   '["Prefer to wait","General conversation ok","Important to align early","Already comfortable talking"]'::jsonb, 2, true, false),
  (1, 45, 'Intimacy & boundaries', 'Boundary around solo adult content or subscriptions in marriage:', 'single',
   '["Not acceptable","Discuss boundaries","Personal freedom","Prefer not to answer here"]'::jsonb, 2, true, false),

  (1, 46, 'Social & community', 'Hosting gatherings at home:', 'likert',
   '["Rarely","Monthly","Often","We love hosting"]'::jsonb, 1, true, false),
  (1, 47, 'Social & community', 'Involvement in charity, mosque, church, or civic groups:', 'single',
   '["Central identity","Regular but limited time","Occasional","Minimal"]'::jsonb, 1.25, true, false),
  (1, 48, 'Social & community', 'Social media visibility of relationship:', 'single',
   '["Very private","Milestones only","Regular posts","We have not discussed"]'::jsonb, 1, true, false),

  (1, 49, 'Reflection', 'One value you refuse to compromise on in marriage (short phrase).', 'text', null, 1, false, false),
  (1, 50, 'Reflection', 'What does a successful week in marriage look like to you?', 'text', null, 1, false, false),
  (1, 51, 'Reflection', 'A habit you are working on that a partner should know about.', 'text', null, 0.75, false, false);
