-- Make the profile-photos bucket private. Photos must be served via
-- short-lived signed URLs generated by /api/photos/sign, gated by the
-- viewer's access (block check, suspension check) — same gate the rest
-- of the app uses.
--
-- For a marriage-minded / shidduch product the heightened modesty and
-- privacy expectations make a publicly-scrapeable photo URL the wrong
-- default. After this migration, deleting a member's account also
-- effectively removes access to their photos (signed URLs expire).

update storage.buckets
   set public = false
 where id = 'profile-photos';

-- The old public-read policy is now moot — clients can't read directly
-- from storage anymore. Drop it so the only access path is via signed
-- URLs generated by service-role server routes.
drop policy if exists "photo_public_read" on storage.objects;

-- Upload policy: keep self-write so the existing client-side upload
-- flow (supabase.storage.from('profile-photos').upload(...)) still works
-- for the authenticated user uploading into their own folder.
drop policy if exists "photo_self_write" on storage.objects;
create policy "photo_self_write"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'profile-photos'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "photo_self_update" on storage.objects;
create policy "photo_self_update"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'profile-photos'
    and auth.uid()::text = (storage.foldername(name))[1]
  )
  with check (
    bucket_id = 'profile-photos'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "photo_self_delete" on storage.objects;
create policy "photo_self_delete"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'profile-photos'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

comment on policy "photo_self_write" on storage.objects is
  'Members may upload photos only into their own user-id folder.';
