-- Make the profile-photos bucket private. Photos must be served via
-- short-lived signed URLs generated by /api/photos/sign or by the
-- server endpoints we updated (discover, viewer, matches, etc.),
-- gated by the viewer's access (block check, suspension check).
--
-- For a marriage-minded / shidduch product the heightened modesty and
-- privacy expectations make a publicly-scrapeable photo URL the wrong
-- default. After this migration, deleting a member's account also
-- effectively removes access to their photos (signed URLs expire).

update storage.buckets
   set public = false
 where id = 'profile-photos';

-- NOTE: the original photo_public_read policy on storage.objects from
-- migration 001 cannot be dropped from a regular SQL Editor session in
-- managed Supabase (storage.objects is owned by supabase_storage_admin
-- and triggers `42501 must be owner of relation objects` errors).
--
-- That policy is effectively NEUTRALIZED by setting public=false above,
-- because Supabase Storage's public REST endpoint refuses access to
-- objects in private buckets before RLS even runs. Signed URLs continue
-- to work because they go through the signed-URL endpoint which uses
-- the service role.
--
-- If you want to drop the old `photo_public_read` policy entirely for
-- cleanliness, do it from the Supabase Dashboard:
--   Storage → Policies tab → find "photo_public_read" → Delete.
-- It is safe to leave in place; nothing reads from it anymore.

-- Verify (purely informational; the migration succeeds either way).
do $$
declare
  is_public boolean;
begin
  select public into is_public from storage.buckets where id = 'profile-photos';
  if is_public then
    raise warning 'profile-photos is still public. Open Supabase Dashboard → Storage → profile-photos → Edit, uncheck Public, and Save.';
  else
    raise notice 'profile-photos is private. Signed URLs only.';
  end if;
end$$;
